### PR TITLE
DMBBB Changes Into Main

### PR DESCRIPTION
**Pull request by Danniyb**
### Type of Change

- [ ] Feature
- [ ] Bug fix
- [X ] Documentation

## Contributors

- @bergasanargya 
- @benfarrah01 
- @BillOchieng 
- @Danniyb 
- @Makell-Logan 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

### CODE REVIEW

**Review by solisa986 — APPROVED** [review]
looks good!

**Review by favourojo — APPROVED** [review]
Everything looks good to me!

**Review by burgess01 — APPROVED** [review]
Good Job!

**Review by Barker0103 — APPROVED** [review]
Everything looks good!

**Review by jjumadinova — APPROVED** [review]
Looks good to me. You can merge this now.

**Pull request merged**
